-- MySQL Script generated by MySQL Workbench
-- Sun 14 Oct 2018 07:30:32 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clinicaMedica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinicaMedica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinicaMedica` DEFAULT CHARACTER SET utf8 ;
USE `clinicaMedica` ;

-- -----------------------------------------------------
-- Table `clinicaMedica`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaMedica`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NULL,
  `nome` VARCHAR(60) NULL,
  `dataNascimento` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaMedica`.`medics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaMedica`.`medics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `crm` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `idUser`),
  INDEX `fk_Medico_Usuario1_idx` (`idUser` ASC),
  CONSTRAINT `fk_Medico_Usuario1`
    FOREIGN KEY (`idUser`)
    REFERENCES `clinicaMedica`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaMedica`.`plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaMedica`.`plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaMedica`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaMedica`.`appointment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idMedic` INT NOT NULL,
  `idUser` INT NOT NULL,
  `idPlan` INT NULL,
  `data_hora` DATETIME NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`, `idMedic`, `idUser`),
  INDEX `fk_Consulta_Paciente1_idx` (`idUser` ASC),
  INDEX `fk_Consulta_Usuario1_idx` (`idMedic` ASC),
  INDEX `fk_Consulta_Convenio1_idx` (`idPlan` ASC),
  CONSTRAINT `fk_Consulta_Paciente1`
    FOREIGN KEY (`idUser`)
    REFERENCES `clinicaMedica`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Usuario1`
    FOREIGN KEY (`idMedic`)
    REFERENCES `clinicaMedica`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Convenio1`
    FOREIGN KEY (`idPlan`)
    REFERENCES `clinicaMedica`.`plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaMedica`.`specializations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaMedica`.`specializations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaMedica`.`procedures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaMedica`.`procedures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `duracao` TIME NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaMedica`.`medic_specialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaMedica`.`medic_specialization` (
  `idMedic` INT NOT NULL,
  `idSpecialization` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idMedic`, `idSpecialization`),
  INDEX `fk_Medico_has_Especialidade_Especialidade1_idx` (`idSpecialization` ASC),
  INDEX `fk_Medico_has_Especialidade_Medico1_idx` (`idMedic` ASC),
  CONSTRAINT `fk_Medico_has_Especialidade_Medico1`
    FOREIGN KEY (`idMedic`)
    REFERENCES `clinicaMedica`.`medics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_has_Especialidade_Especialidade1`
    FOREIGN KEY (`idSpecialization`)
    REFERENCES `clinicaMedica`.`specializations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaMedica`.`appointmentRestrictions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaMedica`.`appointmentRestrictions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idMedic` INT NOT NULL,
  `data` DATE NULL,
  `hora` TIME NULL,
  `diasDaSemana` VARCHAR(14) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Restricao_Medico1_idx` (`idMedic` ASC),
  CONSTRAINT `fk_Restricao_Medico1`
    FOREIGN KEY (`idMedic`)
    REFERENCES `clinicaMedica`.`medics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaMedica`.`documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaMedica`.`documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `observacao` TEXT NULL,
  `path` TEXT NOT NULL,
  PRIMARY KEY (`id`, `idUser`),
  INDEX `fk_Documento_Paciente1_idx` (`idUser` ASC),
  CONSTRAINT `fk_Documento_Paciente1`
    FOREIGN KEY (`idUser`)
    REFERENCES `clinicaMedica`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaMedica`.`medic_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaMedica`.`medic_plan` (
  `id` INT NOT NULL,
  `idMedic` INT NOT NULL,
  `idPlan` INT NOT NULL,
  PRIMARY KEY (`id`, `idMedic`, `idPlan`),
  INDEX `fk_medics_has_plans_plans1_idx` (`idPlan` ASC),
  INDEX `fk_medics_has_plans_medics1_idx` (`idMedic` ASC, `id` ASC),
  CONSTRAINT `fk_medics_has_plans_medics1`
    FOREIGN KEY (`idMedic` , `id`)
    REFERENCES `clinicaMedica`.`medics` (`id` , `idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medics_has_plans_plans1`
    FOREIGN KEY (`idPlan`)
    REFERENCES `clinicaMedica`.`plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaMedica`.`appointment_procedures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaMedica`.`appointment_procedures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idAppointment` INT NOT NULL,
  `idProcedures` INT NOT NULL,
  INDEX `fk_appointment_has_procedures_procedures1_idx` (`idProcedures` ASC),
  INDEX `fk_appointment_has_procedures_appointment1_idx` (`idAppointment` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_appointment_has_procedures_appointment1`
    FOREIGN KEY (`idAppointment`)
    REFERENCES `clinicaMedica`.`appointment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_has_procedures_procedures1`
    FOREIGN KEY (`idProcedures`)
    REFERENCES `clinicaMedica`.`procedures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
